name: Deploy to Hostinger

on:
  push:
    branches:
      - claude/review-punktpass-github-01EJT8MN1vS66AiCrvSPvKXn
      - main
      - master

jobs:
  deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: 89.116.147.72
          username: u660905446.punktepass.de
          password: Brtegk84047+_
          port: 21
          protocol: ftp
          server-dir: /home/u660905446/domains/punktepass.de/public_html/wp-content/plugins/punktepass/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
            **/README.md
            **/.DS_Store
